# Generated by Django 3.2.7 on 2021-10-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_id', models.CharField(default='NA', max_length=20)),
                ('field_notes', models.CharField(default='NA', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=200)),
                ('treatment_notes', models.CharField(default='NA', max_length=1000)),
                ('treatment_type', models.CharField(choices=[('treat', 'Treat'), ('spray', 'Spray'), ('apply', 'Apply'), ('spread', 'Spread')], max_length=100)),
                ('treatment_date', models.DateField(verbose_name='date of action')),
                ('treatment_performer', models.CharField(default='NA', max_length=100)),
                ('treatment_chemical', models.CharField(default='NA', max_length=100)),
                ('treatment_rate', models.FloatField(verbose_name='T/ha')),
                ('treatment_location', models.CharField(default='entire field', max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.field')),
            ],
        ),
        migrations.CreateModel(
            name='Tillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tillage_name', models.CharField(max_length=200)),
                ('tillage_notes', models.CharField(default='NA', max_length=1000)),
                ('tillage_type', models.CharField(choices=[('till', 'Till'), ('plow', 'Plow'), ('rip', 'Rip'), ('chisel', 'Chisel'), ('rock pick', 'Rock Pick'), ('disc', 'Disc')], max_length=100)),
                ('tillage_date', models.DateField(verbose_name='date of action')),
                ('tillage_performer', models.CharField(default='NA', max_length=100)),
                ('tillage_implement', models.CharField(default='NA', max_length=100)),
                ('tillage_location', models.CharField(default='entire field', max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.field')),
            ],
        ),
        migrations.CreateModel(
            name='Terminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminate_name', models.CharField(max_length=200)),
                ('terminate_notes', models.CharField(default='NA', max_length=1000)),
                ('terminate_type', models.CharField(choices=[('terminate', 'Terminate'), ('plow under', 'Plow Under'), ('turn', 'Turn'), ('mow', 'Mow'), ('cut', 'Cut')], max_length=100)),
                ('terminate_date', models.DateField(verbose_name='date of action')),
                ('terminate_performer', models.CharField(default='NA', max_length=100)),
                ('terminate_implement', models.CharField(default='NA', max_length=100)),
                ('terminate_location', models.CharField(default='entire field', max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.field')),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_name', models.CharField(max_length=200)),
                ('planting_notes', models.CharField(default='NA', max_length=1000)),
                ('planting_type', models.CharField(choices=[('planting', 'Planting'), ('seed', 'Seed'), ('transplant', 'Transplant'), ('sow', 'Sow'), ('fill in', 'Fill In')], max_length=100)),
                ('planting_date', models.DateField(verbose_name='date of action')),
                ('planting_performer', models.CharField(default='NA', max_length=100)),
                ('planting_crop', models.CharField(default='NA', max_length=100)),
                ('planting_rate', models.FloatField(verbose_name='seeds/m2')),
                ('planting_location', models.CharField(default='entire field', max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.field')),
            ],
        ),
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_name', models.CharField(max_length=200)),
                ('install_notes', models.CharField(default='NA', max_length=1000)),
                ('install_date', models.DateField(verbose_name='date of action')),
                ('install_performer', models.CharField(default='NA', max_length=100)),
                ('install_location', models.CharField(default='entire field', max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.field')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_name', models.CharField(max_length=200)),
                ('harvest_notes', models.CharField(default='NA', max_length=1000)),
                ('harvest_type', models.CharField(choices=[('harvest', 'Harvest'), ('combine', 'Combine'), ('reap', 'Reap'), ('pick', 'Pick'), ('glean', 'Glean'), ('shell', 'Shell')], max_length=100)),
                ('harvest_date', models.DateField(verbose_name='date of action')),
                ('harvest_performer', models.CharField(default='NA', max_length=100)),
                ('harvest_crop', models.CharField(default='NA', max_length=100)),
                ('harvest_rate', models.FloatField(verbose_name='T/ha')),
                ('harvest_location', models.CharField(default='entire field', max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.field')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=200)),
                ('fertilizer_notes', models.CharField(default='NA', max_length=1000)),
                ('fertilizer_type', models.CharField(choices=[('fertilize', 'Fertilize'), ('spray', 'Spray'), ('inject', 'Inject'), ('spread', 'Spread'), ('sidedress', 'Sidedress')], max_length=100)),
                ('fertilizer_date', models.DateField(verbose_name='date of action')),
                ('fertilizer_performer', models.CharField(default='NA', max_length=100)),
                ('fertilizer_chemical', models.CharField(default='NA', max_length=100)),
                ('fertilizer_rate', models.FloatField(verbose_name='T/ha')),
                ('fertilizer_location', models.CharField(default='entire field', max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.field')),
            ],
        ),
    ]
