# Generated by Django 3.2.7 on 2021-10-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='fertilizer_date',
            field=models.DateTimeField(verbose_name='date of action'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='harvest_date',
            field=models.DateTimeField(verbose_name='date of action'),
        ),
        migrations.AlterField(
            model_name='install',
            name='install_date',
            field=models.DateTimeField(verbose_name='date of action'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='planting_date',
            field=models.DateTimeField(verbose_name='date of action'),
        ),
        migrations.AlterField(
            model_name='terminate',
            name='terminate_date',
            field=models.DateTimeField(verbose_name='date of action'),
        ),
        migrations.AlterField(
            model_name='tillage',
            name='tillage_date',
            field=models.DateTimeField(verbose_name='date of action'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_date',
            field=models.DateTimeField(verbose_name='date of action'),
        ),
    ]
