# Generated by Django 4.1.1 on 2022-10-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chemical_type", models.CharField(max_length=50)),
                ("date_applied", models.DateTimeField()),
                ("amount", models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=50)),
                ("date_planted", models.DateTimeField()),
                ("date_harvest", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_num", models.IntegerField(max_length=5)),
                ("soil_type", models.CharField(max_length=20)),
                ("fallow", models.BooleanField()),
            ],
        ),
    ]
