# Generated by Django 4.1.1 on 2022-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chemical_type", models.CharField(max_length=50)),
                ("date_applied", models.DateField()),
                ("chemical_name", models.CharField(default="chemical", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=50)),
                (
                    "scientific_name",
                    models.CharField(default="sci_name", max_length=50),
                ),
                ("life_form", models.CharField(default="form", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "field_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("soil_type", models.CharField(max_length=50)),
                ("location", models.CharField(default="location", max_length=50)),
            ],
        ),
    ]
