# Generated by Django 4.1.1 on 2022-10-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemical", name="amount", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="field", name="field_num", field=models.IntegerField(),
        ),
    ]
