# Generated by Django 4.1.1 on 2022-10-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0002_alter_chemical_amount_alter_field_field_num"),
    ]

    operations = [
        migrations.RemoveField(model_name="chemical", name="amount",),
        migrations.RemoveField(model_name="crop", name="date_harvest",),
        migrations.RemoveField(model_name="crop", name="date_planted",),
        migrations.RemoveField(model_name="field", name="fallow",),
        migrations.RemoveField(model_name="field", name="field_num",),
        migrations.AddField(
            model_name="chemical",
            name="chemical_name",
            field=models.CharField(default="chemical", max_length=50),
        ),
        migrations.AddField(
            model_name="crop",
            name="life_form",
            field=models.CharField(default="form", max_length=50),
        ),
        migrations.AddField(
            model_name="crop",
            name="scientific_name",
            field=models.CharField(default="sci_name", max_length=50),
        ),
        migrations.AddField(
            model_name="field",
            name="field_name",
            field=models.CharField(default="field_name", max_length=50),
        ),
        migrations.AddField(
            model_name="field",
            name="location",
            field=models.CharField(default="location", max_length=50),
        ),
        migrations.AlterField(
            model_name="field", name="soil_type", field=models.CharField(max_length=50),
        ),
    ]
