# Generated by Django 4.1.1 on 2022-10-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0003_remove_chemical_amount_remove_crop_date_harvest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="field_num",
            field=models.IntegerField(default="num"),
        ),
    ]
