# Generated by Django 4.1.1 on 2022-10-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0004_field_field_num"),
    ]

    operations = [
        migrations.RemoveField(model_name="field", name="id",),
        migrations.AlterField(
            model_name="field",
            name="field_num",
            field=models.IntegerField(default="num", primary_key=True, serialize=False),
        ),
    ]
