# Generated by Django 4.1.1 on 2022-10-02 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmnotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="observation_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
